apiVersion: apps/v1
kind: Deployment
metadata:
  name: basset-diff-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basset-diff
  template:
    metadata:
      labels:
        app: basset-diff
    spec:
      containers:
        - name: basset-diff
          image: getbasset/basset-diff:release-1.0.0-beta-7
          args: ["workers.rabbitmq"]
          envFrom:
            - configMapRef:
                name: basset-diff-config